### ISSUE TITLE
Ошибка Error: not opened

### ISSUE THREAD

**Issue by T1MOXA** [Yashko/node-csgotm#2]
Бот работает какое то время и падает с ошибкой:

```
bot\node_modules\ws\lib\WebSocket.js:219
    else throw new Error('not opened');
         ^
Error: not opened
    at WebSocket.send (bot\node_modules\ws\lib\WebSocket.js:219:16)
    at Timeout.ping [as _onTimeout] (bot\node_modules\csgotm\index.js:74:13)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

**Comment by T1MOXA** [comment]
Сам смог поправить, нужно было добавить одну проверку )
